baseURL = "https://www.example.com"
languageCode = "en-us"
title = "My Digital Garden"
theme = "hugo-digital-garden-theme"
themesdir = "../../"
copyright = "Nigalya Ponya Â©"


[params]
  name = "Nigalya Ponya"
  description = "Red panda living in the eastern Himalayas."
  initials = "NP"
  googleAnalytics = ""

  [[params.sections]]
    name = "now"
    weight = 1
    enable = true
    limit = 1
    display = "full"

  [[params.sections]]
    name = "garden"
    weight = 2
    enable = true
    limit = 2
    display = "list"

  [[params.sections]]
    name = "projects"
    weight = 3
    enable = true
    limit = 2
    display = "grid"

  [[params.sections]]
    name = "library"
    weight = 4
    enable = false
    limit = 3
    display = "grid"

  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "#"
    icon = "fab fa-github"

  [[params.social]]
    name = "Medium" 
    link = "#"
    icon = "fab fa-medium-m"

  [[params.social]]
    name = "LinkedIn"
    link = "#"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[params.fonts]
  title = "Noto Serif SC"
  titleType = "serif"
  titleWeights = "400;700"

  body = "Noto Sans SC"
  bodyType = "sans-serif"
  bodyWeights = "300;400;700"


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'rose-pine-moon'